export type IssueColor =
    | 'dark_grey'
    | 'dark_yellow'
    | 'yellow'
    | 'dark_blue'
    | 'dark_teal'
    | 'green'
    | 'purple'
    | 'dark_purple'
    | 'orange'
    | 'blue'
    | 'teal'
    | 'grey'
    | 'dark_green'
    | 'dark_orange';
